drop table test if exists;

CREATE TABLE TEST (
    STUDENT_NO VARCHAR(10),
    SUBJECT_CD CHAR(3),
    SCHOOL_CD CHAR(10),
    NO INT,
    POINT INT,
    CLASS_NUM VARCHAR(10),
    PRIMARY KEY (STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO)
);
INSERT INTO test VALUES ('2231111','A02','oom',1,100,'131');